/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChangeLog.java
 *
 * Created on Jun 23, 2011, 3:02:17 PM
 */

package mcservergui.gui;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.HttpURLConnection;

/**
 *
 * @author Billing Manager
 */
public class ChangeLog extends javax.swing.JDialog {

    /** Creates new form ChangeLog */
    public ChangeLog(java.awt.Frame parent, String version) {
        super(parent);
        initComponents();
        this.version = version;
        addChangeLog();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeLogPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        changeLogField = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mcservergui.Main.class).getContext().getResourceMap(ChangeLog.class);
        changeLogPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("changeLogPanel.border.title"))); // NOI18N
        changeLogPanel.setName("changeLogPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        changeLogField.setName("changeLogField"); // NOI18N
        jScrollPane1.setViewportView(changeLogField);

        javax.swing.GroupLayout changeLogPanelLayout = new javax.swing.GroupLayout(changeLogPanel);
        changeLogPanel.setLayout(changeLogPanelLayout);
        changeLogPanelLayout.setHorizontalGroup(
            changeLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        changeLogPanelLayout.setVerticalGroup(
            changeLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addChangeLog() {
        String urltext = "https://raw.github.com/dumptruckman/MC-Server-GUI--multi-/master/VERSION";
        String newVersion= "";
        try {
            URL url = new URL(urltext);
            HttpURLConnection huc =  (HttpURLConnection)  url.openConnection();
            huc.setRequestMethod("GET");
            huc.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729)");
            huc.connect();
            if (!(huc.getResponseCode() == 200)) {
                throw new IOException();
            }
            BufferedReader in = new BufferedReader(new InputStreamReader(url
                    .openStream()));
            String line = "";
            if ((line = in.readLine()) != null) {
                newVersion = line;
            }
            in.close();
        } catch (java.net.MalformedURLException e) {
            changeLogField.setText("Error retrieving Change Log");
            return;
        } catch (IOException ioe) {
            changeLogField.setText("Error retrieving Change Log");
            return;
        }
        urltext = "https://raw.github.com/dumptruckman/MC-Server-GUI--multi-/master/CHANGELOG";
        try {
            URL url = new URL(urltext);
            BufferedReader in = new BufferedReader(new InputStreamReader(url
                    .openStream()));
            String line = "";
            String data = "";
            boolean readChanges = false;
            boolean endOnNextVersion = false;
            while ((line = in.readLine()) != null) {
                if (line.startsWith("Version ")) {
                    if (endOnNextVersion) {
                        break;
                    }
                    if (line.startsWith("Version " + newVersion)) {
                        readChanges = true;
                    } //newVersion.equals(version) ||
                    if (line.startsWith("Version " + version)) {
                        readChanges = true;
                        endOnNextVersion = true;
                    }
                }
                if (readChanges) {
                    data += line + System.getProperty("line.separator");
                }
            }
            in.close();
            changeLogField.setText(data);
        } catch (java.net.MalformedURLException e) {
            changeLogField.setText("Error retrieving Change Log");
        } catch (IOException ioe) {
            changeLogField.setText("Error retrieving Change Log");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane changeLogField;
    private javax.swing.JPanel changeLogPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private String version;
}
