/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomTasks.java
 *
 * Created on Jun 21, 2011, 11:32:24 AM
 */

package mcservergui.gui;

/**
 *
 * @author Billing Manager
 */
public class CustomTasks extends javax.swing.JDialog {

    /** Creates new form CustomTasks */
    public CustomTasks(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customTasksLabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customTasksList = new javax.swing.JList();
        addCustomTaskButton = new javax.swing.JButton();
        editCustomTaskButton = new javax.swing.JButton();
        removeCustomTasksButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mcservergui.Main.class).getContext().getResourceMap(CustomTasks.class);
        customTasksLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("customTasksLabel.border.title"))); // NOI18N
        customTasksLabel.setName("customTasksLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        customTasksList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        customTasksList.setName("customTasksList"); // NOI18N
        jScrollPane1.setViewportView(customTasksList);

        javax.swing.GroupLayout customTasksLabelLayout = new javax.swing.GroupLayout(customTasksLabel);
        customTasksLabel.setLayout(customTasksLabelLayout);
        customTasksLabelLayout.setHorizontalGroup(
            customTasksLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        customTasksLabelLayout.setVerticalGroup(
            customTasksLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        addCustomTaskButton.setText(resourceMap.getString("addCustomTaskButton.text")); // NOI18N
        addCustomTaskButton.setName("addCustomTaskButton"); // NOI18N

        editCustomTaskButton.setText(resourceMap.getString("editCustomTaskButton.text")); // NOI18N
        editCustomTaskButton.setName("editCustomTaskButton"); // NOI18N

        removeCustomTasksButton.setText(resourceMap.getString("removeCustomTasksButton.text")); // NOI18N
        removeCustomTasksButton.setName("removeCustomTasksButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customTasksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addCustomTaskButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCustomTaskButton)
                .addGap(18, 18, 18)
                .addComponent(removeCustomTasksButton)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customTasksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomTaskButton)
                    .addComponent(editCustomTaskButton)
                    .addComponent(removeCustomTasksButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomTasks dialog = new CustomTasks(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomTaskButton;
    private javax.swing.JPanel customTasksLabel;
    private javax.swing.JList customTasksList;
    private javax.swing.JButton editCustomTaskButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeCustomTasksButton;
    // End of variables declaration//GEN-END:variables

}
