/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MCServerGUITaskDialog.java
 *
 * Created on May 26, 2011, 10:07:12 PM
 */

package mcservergui;

import org.jdesktop.application.Action;

/**
 *
 * @author Roton
 */
public class MCServerGUITaskDialog extends javax.swing.JDialog {

    /** Creates new form MCServerGUITaskDialog */
    public MCServerGUITaskDialog(java.awt.Frame parent, MCServerGUIListModel taskList, MCServerGUIConfig config) {
        super(parent);
        this.taskList = taskList;
        this.config = config;
        initComponents();
    }

    @Action public void closeTaskDialog() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taskNameLabel = new javax.swing.JLabel();
        taskNameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        secondsLabel = new javax.swing.JLabel();
        secondsField = new javax.swing.JTextField();
        scheduleLabel = new javax.swing.JLabel();
        secondAgainCheckBox = new javax.swing.JCheckBox();
        secondAgainField = new javax.swing.JTextField();
        secondsAllCheckBox = new javax.swing.JCheckBox();
        minutesLabel = new javax.swing.JLabel();
        minutesAgainLabel = new javax.swing.JCheckBox();
        minutesAgainField = new javax.swing.JTextField();
        minutesField = new javax.swing.JTextField();
        minutesAllCheckBox = new javax.swing.JCheckBox();
        hoursLabel = new javax.swing.JLabel();
        hoursField = new javax.swing.JTextField();
        hoursAgainLabel = new javax.swing.JCheckBox();
        hoursAgainField = new javax.swing.JTextField();
        hoursAllCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        dowList = new javax.swing.JList();
        dowLabel = new javax.swing.JLabel();
        dowAllButton = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        monthList = new javax.swing.JList();
        monthLabel = new javax.swing.JLabel();
        monthAllButton = new javax.swing.JToggleButton();
        domButton = new javax.swing.JToggleButton();
        domField = new javax.swing.JTextField();
        domAllCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mcservergui.MCServerGUIApp.class).getContext().getResourceMap(MCServerGUITaskDialog.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        taskNameLabel.setText(resourceMap.getString("taskNameLabel.text")); // NOI18N
        taskNameLabel.setName("taskNameLabel"); // NOI18N

        taskNameField.setText(resourceMap.getString("taskNameField.text")); // NOI18N
        taskNameField.setName("taskNameField"); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        secondsLabel.setText(resourceMap.getString("secondsLabel.text")); // NOI18N
        secondsLabel.setName("secondsLabel"); // NOI18N

        secondsField.setText(resourceMap.getString("secondsField.text")); // NOI18N
        secondsField.setToolTipText(resourceMap.getString("secondsField.toolTipText")); // NOI18N
        secondsField.setInputVerifier(new regexVerifier("^([0-5]?\\d(,\\s?[0-5]?\\d){0,59}|[0-5]?\\d-[0-5]?\\d)$"));
        secondsField.setName("secondsField"); // NOI18N

        scheduleLabel.setText(resourceMap.getString("scheduleLabel.text")); // NOI18N
        scheduleLabel.setName("scheduleLabel"); // NOI18N

        secondAgainCheckBox.setText(resourceMap.getString("secondAgainCheckBox.text")); // NOI18N
        secondAgainCheckBox.setName("secondAgainCheckBox"); // NOI18N

        secondAgainField.setText(resourceMap.getString("secondAgainField.text")); // NOI18N
        secondAgainField.setName("secondAgainField"); // NOI18N

        secondsAllCheckBox.setText(resourceMap.getString("secondsAllCheckBox.text")); // NOI18N
        secondsAllCheckBox.setName("secondsAllCheckBox"); // NOI18N

        minutesLabel.setText(resourceMap.getString("minutesLabel.text")); // NOI18N
        minutesLabel.setName("minutesLabel"); // NOI18N

        minutesAgainLabel.setText(resourceMap.getString("minutesAgainLabel.text")); // NOI18N
        minutesAgainLabel.setName("minutesAgainLabel"); // NOI18N

        minutesAgainField.setName("minutesAgainField"); // NOI18N

        minutesField.setText(resourceMap.getString("minutesField.text")); // NOI18N
        minutesField.setToolTipText(resourceMap.getString("minutesField.toolTipText")); // NOI18N
        minutesField.setInputVerifier(new regexVerifier("^([0-5]?\\d(,\\s?[0-5]?\\d){0,59}|[0-5]?\\d-[0-5]?\\d)$"));
        minutesField.setName("minutesField"); // NOI18N

        minutesAllCheckBox.setText(resourceMap.getString("minutesAllCheckBox.text")); // NOI18N
        minutesAllCheckBox.setName("minutesAllCheckBox"); // NOI18N

        hoursLabel.setText(resourceMap.getString("hoursLabel.text")); // NOI18N
        hoursLabel.setName("hoursLabel"); // NOI18N

        hoursField.setText(resourceMap.getString("hoursField.text")); // NOI18N
        hoursField.setToolTipText(resourceMap.getString("hoursField.toolTipText")); // NOI18N
        hoursField.setInputVerifier(new regexVerifier("^([0-5]?\\d(,\\s?[0-5]?\\d){0,59}|[0-5]?\\d-[0-5]?\\d)$"));
        hoursField.setName("hoursField"); // NOI18N

        hoursAgainLabel.setText(resourceMap.getString("hoursAgainLabel.text")); // NOI18N
        hoursAgainLabel.setName("hoursAgainLabel"); // NOI18N

        hoursAgainField.setName("hoursAgainField"); // NOI18N

        hoursAllCheckBox.setText(resourceMap.getString("hoursAllCheckBox.text")); // NOI18N
        hoursAllCheckBox.setName("hoursAllCheckBox"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        dowList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        dowList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dowList.setName("dowList"); // NOI18N
        jScrollPane1.setViewportView(dowList);

        dowLabel.setText(resourceMap.getString("dowLabel.text")); // NOI18N
        dowLabel.setName("dowLabel"); // NOI18N

        dowAllButton.setText(resourceMap.getString("dowAllButton.text")); // NOI18N
        dowAllButton.setName("dowAllButton"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        monthList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        monthList.setName("monthList"); // NOI18N
        jScrollPane2.setViewportView(monthList);

        monthLabel.setText(resourceMap.getString("monthLabel.text")); // NOI18N
        monthLabel.setName("monthLabel"); // NOI18N

        monthAllButton.setText(resourceMap.getString("monthAllButton.text")); // NOI18N
        monthAllButton.setName("monthAllButton"); // NOI18N

        domButton.setText(resourceMap.getString("domButton.text")); // NOI18N
        domButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        domButton.setName("domButton"); // NOI18N

        domField.setText(resourceMap.getString("domField.text")); // NOI18N
        domField.setToolTipText(resourceMap.getString("domField.toolTipText")); // NOI18N
        domField.setInputVerifier(new regexVerifier("^([0-5]?\\d(,\\s?[0-5]?\\d){0,59}|[0-5]?\\d-[0-5]?\\d)$"));
        domField.setName("domField"); // NOI18N

        domAllCheckBox.setText(resourceMap.getString("domAllCheckBox.text")); // NOI18N
        domAllCheckBox.setName("domAllCheckBox"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scheduleLabel)
                    .addComponent(hoursLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondsLabel)
                            .addComponent(minutesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(secondsField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondAgainCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondAgainField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(secondsAllCheckBox))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(minutesField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minutesAgainLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minutesAgainField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minutesAllCheckBox))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoursAgainLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoursAgainField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoursAllCheckBox))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(taskNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dowLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dowAllButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(monthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthAllButton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(domAllCheckBox)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(domButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(domField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNameLabel)
                    .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scheduleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondsLabel)
                    .addComponent(secondsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondAgainCheckBox)
                    .addComponent(secondAgainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondsAllCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutesLabel)
                    .addComponent(minutesAgainLabel)
                    .addComponent(minutesAgainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutesAllCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursLabel)
                    .addComponent(hoursAgainLabel)
                    .addComponent(hoursAgainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursAllCheckBox)
                    .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dowLabel)
                    .addComponent(dowAllButton)
                    .addComponent(monthLabel)
                    .addComponent(monthAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domButton)
                    .addComponent(domField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domAllCheckBox)))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class regexVerifier extends javax.swing.InputVerifier {
        public regexVerifier(String regex) {
            this.regex = regex;
        }
        
        @Override public boolean verify(javax.swing.JComponent input) {
            javax.swing.JTextField tf = (javax.swing.JTextField) input;
            if (java.util.regex.Pattern.matches(regex, tf.getText())){
                return true;
            } else {
                tf.getActionMap().get("postTip").actionPerformed(
                        new java.awt.event.ActionEvent(
                        tf, java.awt.event.ActionEvent.ACTION_PERFORMED, "postTip"));
                return false;
            }
        }

        String regex;
    }

    private MCServerGUIListModel taskList;
    private MCServerGUIConfig config;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox domAllCheckBox;
    private javax.swing.JToggleButton domButton;
    private javax.swing.JTextField domField;
    private javax.swing.JToggleButton dowAllButton;
    private javax.swing.JLabel dowLabel;
    private javax.swing.JList dowList;
    private javax.swing.JTextField hoursAgainField;
    private javax.swing.JCheckBox hoursAgainLabel;
    private javax.swing.JCheckBox hoursAllCheckBox;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField minutesAgainField;
    private javax.swing.JCheckBox minutesAgainLabel;
    private javax.swing.JCheckBox minutesAllCheckBox;
    private javax.swing.JTextField minutesField;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JToggleButton monthAllButton;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JList monthList;
    private javax.swing.JLabel scheduleLabel;
    private javax.swing.JCheckBox secondAgainCheckBox;
    private javax.swing.JTextField secondAgainField;
    private javax.swing.JCheckBox secondsAllCheckBox;
    private javax.swing.JTextField secondsField;
    private javax.swing.JLabel secondsLabel;
    private javax.swing.JTextField taskNameField;
    private javax.swing.JLabel taskNameLabel;
    // End of variables declaration//GEN-END:variables

}
